//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPB.LogicApp.Standard.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPB.LogicApp.Standard.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	actionStatus = logicAppTestManager.GetActionStatus(&quot;{{ActionName}}&quot;);
        ///	Assert.AreEqual(actionStatus, ActionStatus.{{ActionName}});.
        /// </summary>
        internal static string SampleActionAssertion {
            get {
                return ResourceManager.GetString("SampleActionAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     public void Test()
        ///    {
        ///        var actionStatus = ActionStatus.Succeeded;
        ///
        ///        //Arrange
        ///        var workflowName = &quot;{{WorkflowName}}&quot;;
        ///        var logicAppTestManager = LogicAppTestManagerBuilder.Build(workflowName);
        ///
        ///        var request = &quot;{{Request}}&quot;;
        ///
        ///        //TODO: Check your content type
        ///        var content = new StringContent(request, Encoding.UTF8, &quot;application/json&quot;);
        ///       
        ///        //Act
        ///        var response = logicAppTestManager.TriggerLogicAppWithPost(content);
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleTestCode {
            get {
                return ResourceManager.GetString("SampleTestCode", resourceCulture);
            }
        }
    }
}
